kind: pipeline
name: default
type: kubernetes
steps:
  - name: Build
    image: node
    commands:
      - "npm install"
      - "mkdir -p dist/webApp"
      - "npm run build --configuration==${DRONE_SOURCE_BRANCH}"
  
  - name: Analysis
    image: aosapps/drone-sonar-plugin
    settings:
      sonar_host:
        from_secret: sonar_host
      sonar_token:
        from_secret: sonar_token

  - name: Notify
    image: appleboy/drone-telegram
    when:
      status: [ success, failure ]
    settings:
      token:
        from_secret: telegram_token
      to: 150678964

trigger:
  branch:
    - master
    - release
    - develop
  event:
  - push
  - promote

---

kind: pipeline
type: kubernetes
name: deploy

steps:
  - name: Dockerize & Publish
    image: plugins/docker
    settings:
      registry: metalcloud.azurecr.io
      repo: metalcloud.azurecr.io/frontend
      username:
        from_secret: registry_username
      password:
        from_secret: registry_password
      tags: "v1.${DRONE_BUILD_NUMBER}-${DRONE_DEPLOY_TO}"
  
  - name: Deploy
    image: ubuntu
    settings:
      command:
        - "echo ${DRONE_DEPLOY_TO}"

trigger:
  event:
  - promote
  target:
    include:
    - dev
    - qa

depends_on:
  - default

---

kind: pipeline
type: kubernetes
name: deploy-prod

steps:

  - name: GIT Tag
    image: docker:git
    commands:
      - git tag v1.${DRONE_BUILD_NUMBER}-${DRONE_DEPLOY_TO}
      - git push origin v1.${DRONE_BUILD_NUMBER}-${DRONE_DEPLOY_TO}

trigger:
  event:
  - promote
  target:
    - prod

depends_on:
  - default
