kind: pipeline
name: default
type: kubernetes
steps:
  - name: Build
    image: node
    commands:
      - "npm install"
      - "mkdir -p dist/webApp"
      - "npm run build"
  
  - name: Analysis
    image: aosapps/drone-sonar-plugin
    settings:
      sonar_host:
        from_secret: sonar_host
      sonar_token:
        from_secret: sonar_token
  
  - name: Dockerize & Publish  
    image: plugins/docker
    settings:
      username:
        from_secret: registry_username
      password:
        from_secret: registry_password
      registry:
        from_secret: registry_host
      repo: metalcloud/frontend
      tags: latest
  
  - name: Notify
    image: appleboy/drone-telegram
    when:
      status: [ success, failure ]
    settings:
      token:
        from_secret: telegram_token
      to: 522942451
      format: markdown
      message: >
        {{#success build.status}}
        ✅ Compilacion #{{build.number}} de `{{repo.name}}` exitosa. Buen trabajo!.

        📝 Commit por {{commit.author}} en `{{commit.branch}}`:

        ```
        {{commit.message}}
        ```

        🌐 {{ build.link }}
        {{else}}
        ❌ Compilacion #{{build.number}} de `{{repo.name}}` con errores. Por favor revisar.

        📝 Commit por {{commit.author}} en `{{commit.branch}}`:

        ```
        {{commit.message}}
        ```

        🌐 {{ build.link }}
        {{/success}}
