kind: pipeline
name: default
type: kubernetes
steps:
  - name: Build
    image: node
    commands:
      - "npm install"
      - "mkdir -p dist/webApp"
      - "npm run build"
  
  - name: Analysis
    image: aosapps/drone-sonar-plugin
    settings:
      sonar_host:
        from_secret: sonar_host
      sonar_token:
        from_secret: sonar_token
  
  - name: Dockerize & Publish  
    image: plugins/docker
    settings:
      registry: metalcloud.azurecr.io
      repo: metalcloud.azurecr.io/frontend
      username:
        from_secret: registry_username
      password:
        from_secret: registry_password
      tags: latest
  
  - name: Notify
    image: appleboy/drone-telegram
    when:
      status: [ success, failure ]
    settings:
      token:
        from_secret: telegram_token
      to: 150678964


---

kind: pipeline
name: default
type: kubernetes
trigger:
  